channels:
- conda-forge
dependencies:
- python=3.11.9
- pip<=24.2
- pip:
  - mlflow==2.12.1
  - cffi==1.16.0
  - cloudpickle==3.1.2
  - graphviz==0.20.3
  - importlib-metadata==6.11.0
  - jinja2==3.1.4
  - matplotlib==3.7.5
  - numpy==1.26.4
  - packaging==24.1
  - pandas==2.1.4
  - pyarrow==15.0.2
  - pycaret==3.3.2
  - pyyaml==6.0.1
  - scikit-learn==1.4.2
  - scipy==1.11.4
name: mlflow-env
